---
title: "ninis_vih"
author: "Jazmín Qquellon"
date: "3/10/2021"
output: html_document
---

```{r}

library(tidyverse)
library(haven)
library(gtsummary)
library(survey)

```
# Gestantes 2020

```{r}
gestacion1 <- read_sav("./endes_data/2020/RE223132.sav")
gestacion2 <- read_sav("./endes_data/2020/REC94.sav") # outcome # id

violence <- read_sav("./endes_data/2020/REC84DV.sav")

sociodemo <- read_sav("./endes_data/2020/REC0111.sav")

vih1 <- read_sav("./endes_data/2020/RE758081.sav")
vih2 <- read_sav("./endes_data/2020/REC91.sav")

programas <- read_sav("./endes_data/2020/Programas Sociales x Hogar.sav") ## id


# Gestantes

df_gestantes<-
  gestacion2 %>% 
  left_join(gestacion1, by = "CASEID") %>% 
  left_join(violence, by = "CASEID") %>% 
  left_join(sociodemo, by = "CASEID") %>%
  left_join(vih1, by = "CASEID") %>% 
  left_join(vih2, by = "CASEID") %>%
  
  mutate(
    HHID = as.numeric(str_sub(CASEID,1,-3)),
    
  ) %>% 
  left_join(programas %>% 
              mutate(
                HHID = as.numeric(HHID)),by = "HHID")


```

# EDA

```{r}
sociodemo<-
  sociodemo %>% 
  mutate(
    V102 = as.factor(V102),
    V005 = V005/1000000
  )
```


```{r}
df2<- svydesign(id =~ V001, strata =~ V022, weights=~V005, data= sociodemo)
options(survey.lonely.psu="remove")

svymean(~V102, design = df2, na.rm = T)
```



